- README.md
- src/vue-property-decorator.ts
This way we can get rid of the `allowSyntheticDefaultImports` option and reduce our import to a single statement:
```js
import { Component, Prop, Vue} from 'vue-property-decorator'
@Component
export default class MyComponent extends Vue {
@Prop()
name: string
}
```
> Please also export Vue

- src/vue-property-decorator.ts
- test/decorator.spec.ts
The `@Model` decorator adds the information about which property is used for `v-model`.
In the specifications, we also have to declare the property for it to be given to the component.
If my component is written like this :
```
...
@Model('input')
value
...
```
When the component changes the value, the event is emitted and the parent bound data is changed. Now, if the parent bound data changed, the component' `value` won't change : because `value` is not a propriety.
For it to work as expected (for the binding parent->component to be effective) we also have to declare the property like this : 
```
...
@Model('input')
@Prop()
value
...
```
Because `@Model` always demands a `@Prop`, I propose here to add to the `@Model` decorator the declaration as a property, for it is counter-intuitive to …
> model as prop

- .gitignore
- rollup.config.js
- src/vue-property-decorator.ts
This PR resolve following error with rollup
```
[10:39:37] Error in plugin 'gulp-rollup'
Message:
'Component' is not exported by node_modules\vue-property-decorator\lib\vue-property-decorator.umd.js
Details:
code: MISSING_EXPORT
url: https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
pos: 1241
loc: [object Object]
frame: 19:  import { Component } from 'vue-property-decorator';
21: import { Component } from 'vue-property-decorator';
^
```
Before this PR is should manually define named export for rollup
```js
rollup({
plugins: [
cjs({
namedExports: {
'vue-property-decorator': [ 'Component' ]
}
})
]
})
```
> Named export

- README.md
- src/vue-property-decorator.ts
- test/decorator.spec.ts
Vue 2.5 supports defaultValues for Inject: https://gist.github.com/yyx990803/9bdff05e5468a60ced06c29c39114c6b#inject-with-default-values
I have added the option to the @Inject decorator. Hope this can be added to the next release.
But i failed to run the tests locally. Did yarn run test and got some errors in already existing tests.
> updated @Inject to support defaultValues for vue 2.5

- package.json
- src/vue-property-decorator.ts
- test/decorator.spec.ts
- yarn.lock
[PR/100 ](https://github.com/kaorun343/vue-property-decorator/pull/100) changes [have broken](https://github.com/kaorun343/vue-property-decorator/pull/100/files/942e09cdf5297b374625d4319c5273da3b9ab609..d91fd3b77a8e3abf5e37138127ece518ebd807b1) source code. I fixed mixins so they compile, but mixin tests that had been added in previous PR still fail. Nevertheless mixins code seems to work ok. If I have more time I'll contribute later.
> Fixed uncompiled source code after mixins PR

- package.json
- yarn.lock
updates the dependency of Vue Class Component to get a few bug fixes from upstream. There are no breaking changes between 6.2.0 -> 7.0.1 (https://github.com/vuejs/vue-class-component/releases)
> Update Vue Class Component dependency to latest version

- README.md
Function arguments are also emitted other than the returned value. 
This has made me confused for a while. So add an example to better explain the current behavior of `@Emit` although I don't like it.
> doc: update readme for @Emit

- src/vue-property-decorator.ts
`@Emit` decorator is handling the decorated function's promise but not returning it. This causes issues like not being able to get the result calling the decorated method or the prevention of a right exception propagation. One example of the latest is demonstrated [in this fiddle](https://jsfiddle.net/tjch2b3s/).
Returning the promise or value we let another functions and decorators to handle it.
> fix @Emit return value to make it transparent

- src/vue-property-decorator.ts
- test/decorator.spec.ts
Based on the request in #39 
I thought this would be a nice feature to have, so I took a crack at implementing it. If this is acceptable to merge, I'm happy to add documentation to the README!
_**One gotcha...**_
When using `@ProvideReactive` with `@Prop`, you must use `@Inject`—_not_ `@InjectReactive`—to use the injected property as a `default`... see the coverage for an example of this.
> Add @ProvideReactive and @InjectReactive decorators

- README.md
- src/vue-property-decorator.ts
- test/decorator.spec.ts
It works just like @Prop other than it takes the propName as an argument of the decorator, in addition to it creates a computed getter and setter behind the scenes. This way you can interface with the property as it was a regular data property whilst making it as easy as appending the .sync modifier in the parent component.
I have created tests and written some documentation for the feature, but please come with some feedback or questions if anything is unclear or seems funky.
> Add @PropSync decorator to more easier handle .sync modifier on props

- README.md
- src/vue-property-decorator.ts
- test/decorator.spec.ts
Inspired by https://angular.io/api/core/ViewChild.
[Vue#$refs](https://vuejs.org/v2/api/#vm-refs) is generally typed as `{ [key: string]: Vue | Element | Vue[] | Element[] }`, and using it in TypeScript often requires a type cast. The proposed decorator tries to simplify its usage.
> Add new decorator `Ref`

- README.md
Hi,
I just started using vue / vue-property-decorator / typescript so it is possible I dont fully understand some important details but when I was reading readme I think I noticed a mistake. In @Prop usage example `propA` and `propC` are marked as required by having `!` so undefined type should not be allowed on those props. I prepared a PR so if indeed this is a mistake in readme lets fix it.
Cheers!
> Update prop obligatory and type definition in readme

- package.json
When this package is used in a project that has a modified Vue type (like using i18n or so), the decorators of this project give error because the output type is not matching (it does pick the vue package installed inside the package folder).
With this change the decorator inherits the type from the project instead of the local one and thus not giving any error.
This solution comes from what the official vue-class-component package is doing.
https://github.com/vuejs/vue-class-component/blob/master/package.json#L65
> Vue typing issue solved

- src/vue-property-decorator.ts
- tests/ProvideReactive.spec.ts
@Provide() and @ProvideReactive() were not compatible.
... they are now. See #249
> Fix  Provide/ProvideReactive compatibility (#249)

- src/vue-property-decorator.ts
- tests/Provide.spec.ts
- tests/ProvideReactive.spec.ts
See the new test in ProvideReactive.spec.ts, but long story short: Using `@ProvideReactive()` in a child component overrides all parent dependencies provided using the same method.
For instance, when:
- Component A provides 'X'
- Component B, child of A, provides 'Y'
- Component C uses both 'X' & 'Y'
Then 'Y' is injected, but not 'X'.
This commit fixes it (& adds some test to check that this scenario works for both `@Provide` and `@ProvideReactive`
> Fix @ProvideReactive() inheritance issue

- src/vue-property-decorator.ts
This PR addresses the discussion for issue #249 . 
There was a previous commit that aimed to address this issue (PR #264 ), but that actually broke it further.
The problem arises because both the @Provide and @ProvideReactive decorators are competing to install a provide function in the component options. So whichever one is used first is the one who wins (because of the condition that was there to avoid doing it more than once).
The strategy taken in this fix is to have only one possible provide function, which is aware of both regular injections and reactive injections, and will produce the appropriate provide options object with both types of properties.
As it is now, this feature is broken in the 8.3.0 release, so hopefully this fix can be approved for a minor number release in the …
> Issue # 249: Cannot use @Provide and @ProvideReactive simultaneously.

- src/vue-property-decorator.ts
Sometimes the Emit decorator return 2 values repeated when the correct is only 1..
> Fix Emit decorator

- package.json
This is needed for Yarn 2 compatibility with Plug'n'Play.
> Yarn 2: Add vue as a peer dependency

- src/vue-property-decorator.ts
- tests/Emit.spec.ts
When using Emit with multiple arguments, it will not work properly.
Maybe because the arguments are passed as an array
https://github.com/kaorun343/vue-property-decorator/commit/b9f0ba86b1b0a58164a19aba07ae82836a6c57a9#diff-a542f5e3653e6b2d1bd03489368849b9R269
> Fix Emit Decorator with multiple arguments

- README.md
- src/vue-property-decorator.ts
- tests/ModelSync.spec.ts
@kaorun343 
inspired from https://github.com/kaorun343/vue-property-decorator/issues/86, https://github.com/kaorun343/vue-property-decorator/pull/204
```ts
import { Vue, Component, ModelSync } from 'vue-property-decorator'
@Component
export default class YourComponent extends Vue {
@ModelSync('checked', 'change', { type: Boolean }) readonly checkedValue!: boolean
}
```
is equivalent to
```js
export default {
model: {
prop: 'checked',
event: 'change'
},
props: {
checked: {
type: Boolean
}
},
computed: {
checkedValue: {
get() {
return this.checked
},
set(value) {
this.$emit('change', value)
}
}
}
}
```
`@ModelSync` property can also set `type` property from its type definition via `reflect-metadata` .
Don't need to write the accessor for model, like as `@PropSync`
> Proposal: @ModelSync

- src/vue-property-decorator.ts
When producing a provide function for ProvideReactive the properties are defined as not configureable. This causes a TypeError when unmounting and mounting again a component that uses `@ProvideReactive` because the provide function is called again and tries to redefine a non configureable property.
Referenced here:
https://github.com/kaorun343/vue-property-decorator/issues/313#issuecomment-641834471
make it configurable
> Configureable provide reactive properties.

- README.md
Because that's what's being exported in
https://github.com/kaorun343/vue-property-decorator/blob/2268e895facd3d5e4f912be83a00857fe07a8b64/src/index.ts#L2
> Fix README typo @Option -> @Options
